[workspace]
members = ['crates/*']
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"

[profile.dev]
split-debuginfo = "unpacked"

[profile.release]
incremental = true
debug = false
lto = "thin"
opt-level = "s"
